spring.application.name=tradelog-sentinel

spring.datasource.url=jdbc:postgresql://localhost:5432/tradelog
spring.datasource.username=sooyeonkim
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true